# Generated by Django 4.2.1 on 2023-05-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Name of the hardware type, like laptop, monitor, etc.', max_length=45)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
    ]
